In [2]:
import numpy as np

In [2]:
# numpy(object, dtype = None)
a = np.array([1, 2, 3, 4])
print(a.dtype)

int64


In [3]:
a = np.array(['1', '2', '3', True])
print(a.dtype)

<U5


In [4]:
print(a[0])

1


In [6]:
a[1] = '123'
print(a)

['1' '123' '3' 'True']


In [7]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2])

3


In [11]:
print(a[[1,1,1,1,1,1,1,1,1]])

[2 2 2 2 2 2 2 2 2]


In [10]:
print(a[[True, True, False, False, False, False, True, True, True]])

[1 2 7 8 9]


In [12]:
b = a.reshape(3, 3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(b[1][2])

6


In [14]:
# Основные типы данных. Создание массивов функцией array
a = np.array([1, 2, 3, 4])
print(a)
a = np.array([1, 2, 3, 4], 'float64')
print(a)

[1 2 3 4]
[1. 2. 3. 4.]


In [15]:
print(np.complex64(10))

(10+0j)


In [16]:
print(np.int64(10.5))

10


In [19]:
a = np.array([1, 2, 5000, 1000])
print(np.int8(a))

[   1    2 -120  -24]


In [20]:
b = np.complex64(a)
print(b)
c = np.int32(b)
print(c)

[1.e+00+0.j 2.e+00+0.j 5.e+03+0.j 1.e+03+0.j]
[   1    2 5000 1000]


/var/folders/l9/88y_46d53y3cy1jh1h6qdg0c0000gn/T/ipykernel_76261/2879839655.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  c = np.int32(b)


In [21]:
print(np.array('Hello'))

Hello


In [24]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [27]:
# Функции автозаполнения, создания матриц и числовых диапазонов
print(np.array([0] * 10))
print(np.array([1] * 15))
print(np.array([x for x in range(10)]))
# но эти способы создания массивов работают медленнее,
# чем встроенные функции создания определенных видов массивов

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]


In [33]:
# np.empty(shape, ...) - возвращает новый массив заданного размера и типа данных, но без определенных значений
# np.eye(N, M = None, ...) - возвращает массив размером N*M с единичными диагональными элементами (остальные 0)
# np.identity(n, ...) - возвращает квадратный массив размерностью n*n с единичными элементами по главной диагонали (остальные 0)
# np.ones(shape, ...) - возвращает массив заданного размера и типа, состоящего из единиц
# np.zeros(shape, ...) - то же, что и ones, но с нулями
# np.full(shape, value) - возвращает массив заданного размера и типа со значениями value

print(np.empty(10))
print(np.empty(10, dtype = 'int64'))
print(np.empty((3, 2), dtype = 'int16'), end = '\n\n')

print(np.eye(4))
print(np.eye(4, 2), end = '\n\n')

print(np.identity(5), end = '\n\n')

print(np.zeros((2, 3, 4)), end = '\n\n')

print(np.ones([4, 3], dtype = 'int8'), end = '\n\n')

print(np.full((3, 2), -1))

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323 3.5e-323
 4.0e-323 4.4e-323]
[0 1 2 3 4 5 6 7 8 9]
[[257 257]
 [257 257]
 [257 257]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

[[-1 -1]
 [-1 -1]
 [-1 -1]]


In [36]:
# np.mat(object, ...) - приводит входные данные object к матрице, если это возможно. Параметр object может быть строкой, списком или кортежем
# np.diag(list, ...) - формирует диагональную матрицу на основе списка или массива. Возвращает копию массива
# np.diagflat(list, ...) - формирует диагональную матрицу из списка list, который сначала сжимает до одной оси(преобразует в одномерный список или массив)
# np.tri(N, M = None, ...) - создает треугольный массив N*M с единицами на главной диагонали и ниже ее
# np.tril(list, ...) - преобразует двумерный список или массив list в треугольную матрицу с нулевыми элементами выше главной диагонали
# np.triu(list, ...) - преобразует двумерный список или массив list B треугольную матрицу с нулевыми элементами ниже главной диагонали.
# np.vander(list, N = None, ...) - создание матрицы Вандермонда из одномерного списка или массива list. Второй параметр N определяет ЧИСЛО столбцов (по умолчанию формируется квадратная матрица).

print(np.mat([[1, 2, 3, 4]]))
print(np.mat('1, 2, 3, 4'))
print(np.mat('1 2; 3 4'))
print(np.mat([5, 4, 3]))
print(np.mat([(1, 2, 3), (4, 5, 6)]), end = '\n\n')

print(np.diag([1, 2, 3]))
print(np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)]), end = '\n\n')

print(np.diagflat([(1, 2, 3), (4, 5, 6), (7, 8, 9)]), end = '\n\n')

print(np.tri(4))
print(np.tri(4, 2))
print(np.tri(2, 4), end = '\n\n')

a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(np.tril(a))
print(np.triu(a))
print(np.tril([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]))
print(np.tril([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 20, 30], [40, 50, 60], [70, 80 ,90]], [[100, 200, 300], [400, 500, 600], [700, 800, 900]]]), end = '\n\n')

print(np.vander([1, 2, 3]))

[[1 2 3 4]]
[[1 2 3 4]]
[[1 2]
 [3 4]]
[[5 4 3]]
[[1 2 3]
 [4 5 6]]

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 5 9]

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]
[[1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]]

[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[[1 0 0]
  [4 5 0]
  [7 8 9]]]
[[[  1   0   0]
  [  4   5   0]
  [  7   8   9]]

 [[ 10   0   0]
  [ 40  50   0]
  [ 70  80  90]]

 [[100   0   0]
  [400 500   0]
  [700 800 900]]]

[[1 1 1]
 [4 2 1]
 [9 3 1]]


In [39]:
# np.arange(start = 0, stop, step) - возвращает одномерный массив с равномерно разнесенными числами указанного диапазона.
# np.linspace(start, stop, ...) - Возвращает одномерный массив с равномерно разнесенными. числами. Используя ТОЛЬКО значения начала и конца интервала
# np.logspace(start, stop, ...) - Возврашает одномерный массив с числами. равномерно распределенных по логарифмической шкале.
# np.geomspace(start, stop, ...) - формирование чисел по геометрической прогрессии
# np.meshgrid(x_1, ..., x_n, ...) - x_1..... х_n - одномерные последовательности или массивы. используемые Для формировання координатной сетки по каждой из осей.
# np.mgrid[] - возвращает массив плотных координатных сеток
# np.ogrid[] - возвращает открытую сетку значений

print(np.arange(5))
print(np.arange(1, 5))
print(np.arange(1, 5, 0.5))
print(np.arange(0, np.pi, 0.1))
print(np.cos(np.arange(0, np.pi, 0.1)), end = '\n\n')

print(np.linspace(0, np.pi, 0))
print(np.linspace(0, np.pi, 1))
print(np.linspace(0, np.pi, 2))
print(np.linspace(0, np.pi, 3), end = '\n\n')

print(np.logspace(0, 1, 3))
print(np.logspace(0, 1, 4), end = '\n\n')

print(np.geomspace(1, 4, 3))
print(np.geomspace(1, 16, 5))

[0 1 2 3 4]
[1 2 3 4]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1]
[ 1.          0.99500417  0.98006658  0.95533649  0.92106099  0.87758256
  0.82533561  0.76484219  0.69670671  0.62160997  0.54030231  0.45359612
  0.36235775  0.26749883  0.16996714  0.0707372  -0.02919952 -0.12884449
 -0.22720209 -0.32328957 -0.41614684 -0.5048461  -0.58850112 -0.66627602
 -0.73739372 -0.80114362 -0.85688875 -0.90407214 -0.94222234 -0.97095817
 -0.9899925  -0.99913515]

[]
[0.]
[0.         3.14159265]
[0.         1.57079633 3.14159265]

[ 1.          3.16227766 10.        ]
[ 1.          2.15443469  4.64158883 10.        ]

[1. 2. 4.]
[ 1.  2.  4.  8. 16.]


In [43]:
# array(object, ...) - преобразует список или кортеж object в массив NumPy.
# asanyarray(list, ...) - преобразует список list в массив атау, сохраняя тип подкласса.
# ascontiguousarray(list, ...) - возвращает непрерывный массив в памяти, подобно как это организовано в языке С
# asmatrix(list, ...) - преобразует входную последовательность list B матрицу NumPy (Tun matrix).
# copy(list, ...) - возвращает копию массива list (если это обьект NumPy) или просто создает массив на основе списка языка Python.
# frombuffer(buffer, ...) - преобразует данные из буфера в массив NumPy
# fromfile(file, ...) - возвращает массив из данных текстового или бинарного файла file.
# fromfunction(func, shape, ...) - создает массив размерностью shape с помощью функции func
# fromiter(iter, ...) -  создает массив на основе итерируемого обьекта
# fromstring(string, ...) - создает массив из данных строки
# loadtxt(file, ...) - формирует массив из данных текстового файла

a = np.array([(1, 2), (3, 4)])
print(a)
b = np.copy(a)
print(b[0])
print(a, end = '\n\n')

def getRange(x, y):
    return 100 * x + y
print(np.fromfunction(getRange, (2, 2)))
print(np.fromfunction(lambda x, y: x*100 + y, (2, 2)), end = '\n\n')

print(np.fromiter('hello', dtype = 'U1'))
def getRange(N):
    for i in range(N):
        yield i
print(np.fromiter(getRange(4), dtype = 'int8'), end = '\n\n')

print(np.fromstring('1 2 3', dtype = 'int16', sep = ' '))
print(np.fromstring('1, 2, 3', dtype = 'int16', sep = ','))

[[1 2]
 [3 4]]
[1 2]
[[1 2]
 [3 4]]

[[  0.   1.]
 [100. 101.]]
[[  0.   1.]
 [100. 101.]]

['h' 'e' 'l' 'l' 'o']
[0 1 2 3]

[1 2 3]
[1 2 3]


In [48]:
# Свойства и представления массивов, создание их копий
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
print(a.dtype)
a.dtype = np.int8()
print(a, a.size,  a.dtype, end = '\n\n')
a.dtype = np.float64()
print(a, end = '\n\n')
a.dtype = 'float32'
print(a, a.size, a.itemsize, end = '\n\n') # itemsize показывает, сколько байт занимает элемент массива в пямяти
a.dtype = 'float64'
print(a.itemsize, a.size * a.itemsize)

float64
[-102 -103 -103 -103 -103 -103  -71   63 -102 -103 -103 -103 -103 -103
  -55   63   51   51   51   51   51   51  -45   63 -102 -103 -103 -103
 -103 -103  -39   63    0    0    0    0    0    0  -32   63   51   51
   51   51   51   51  -29   63  102  102  102  102  102  102  -26   63
 -102 -103 -103 -103 -103 -103  -23   63  -51  -52  -52  -52  -52  -52
  -20   63] 72 int8

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

[-1.58818684e-23  1.44999993e+00 -1.58818684e-23  1.57499993e+00
  4.17232506e-08  1.64999998e+00 -1.58818684e-23  1.69999993e+00
  0.00000000e+00  1.75000000e+00  4.17232506e-08  1.77499998e+00
  2.72008302e+23  1.79999995e+00 -1.58818684e-23  1.82499993e+00
 -1.07374184e+08  1.84999990e+00] 18 4

8 72


In [51]:
b = np.ones((3, 4, 5))
print(b.ndim, b.shape, end = '\n\n')
b.shape = 60
print(b, end = '\n\n')
b.shape = 12, 5
print(b)
c = b.reshape(3, 2, 10)
print(c)

3 (3, 4, 5)


In [73]:
# Изменение формы массивов, добавление и удаление осей
a = np.arange(10)
print(a, end = '\n\n')
a.shape = 2, 5
print(a, end = '\n\n')
b = a.reshape(10)
print(b, end = '\n\n')
b[0] = -1
print(a)  # reshape создает новое представление уже существующего массива, а не новый массив

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1 2 3 4 5 6 7 8 9]

[[-1  1  2  3  4]
 [ 5  6  7  8  9]]


In [58]:
a = np.arange(10)
print(np.reshape(a, (-1, 2)))  # если указываем в одном из параметров кортежа 
# при изменении массива отрицательное число, массив переструктурируется так, как будет возможно
print(a.reshape(-1, 5))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [75]:
a = np.arange(10).reshape(2, 5)
print(a, end = '\n\n')
print(a.ravel())  # .ravel() преобразует любой массив в вектор с размерностью 1
a = np.arange(10).reshape(2, 5)
a.shape = -1  # или можно сделать так

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1 2 3 4 5 6 7 8 9]


In [74]:
a = np.arange(10)
a.resize(3, 3, refcheck = False) # если пользуемся методом resize, его можно использовать с параметром refcheck = False, тогда resize точно сработает, хоть иногда и с потерей данных
print(a, end = '\n\n')
a.resize(4, 5, refcheck = False) # в случае если массив, который мы хотим получить методом resize больше изначального, недостающие элементы будут заполнены нулями
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2 3 4]
 [5 6 7 8 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [64]:
a = np.array([(1, 2, 3), (1, 4, 9), (1, 8, 27)])
print(a, end = '\n\n')
print(a.T, end = '\n\n')
x = np.arange(1, 10)
print(x, end = '\n\n')
print(x.T, end = '\n\n') # одномерные массивы - вектора - не могут быть транспонированы, они так и останутся строками, потому что чтобы сделать из массива (1, 9) массив (9, 1) нужно расширить размерность
x.shape = 1, -1
print(x.T)

[[ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]]
[[ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [8]:
x_test = np.arange(32).reshape(8, 2, 2)
print(x_test.shape, end = '\n\n')
x_test4 = np.expand_dims(x_test, axis = 0)
print(x_test4.shape, end = '\n\n')
x_test4[0][0][0][0] = -100
print(x_test[0][0][0], end = '\n\n')  # то есть функция expand_dims создает лишь новое представление массива, а не новый массив, о чем следует помнить
a = np.append(x_test4, x_test4, axis = 0)
print(a.shape, end = '\n\n')
print(a, end = '\n\n')
b = np.delete(a, 0, axis = 0)
print(b.shape, end = '\n\n')
b = np.expand_dims(x_test4, axis = -1)
print(b.shape, end = '\n\n')
c = np.squeeze(b)  # функция squeeze удаляет все оси, значения по которым равны 1
print(c.shape, end = '\n\n')
c = np.squeeze(b, axis = 0)
print(c.shape)

(8, 2, 2)

(1, 8, 2, 2)

-100

(2, 8, 2, 2)

[[[[-100    1]
   [   2    3]]

  [[   4    5]
   [   6    7]]

  [[   8    9]
   [  10   11]]

  [[  12   13]
   [  14   15]]

  [[  16   17]
   [  18   19]]

  [[  20   21]
   [  22   23]]

  [[  24   25]
   [  26   27]]

  [[  28   29]
   [  30   31]]]


 [[[-100    1]
   [   2    3]]

  [[   4    5]
   [   6    7]]

  [[   8    9]
   [  10   11]]

  [[  12   13]
   [  14   15]]

  [[  16   17]
   [  18   19]]

  [[  20   21]
   [  22   23]]

  [[  24   25]
   [  26   27]]

  [[  28   29]
   [  30   31]]]]

(1, 8, 2, 2)

(1, 8, 2, 2, 1)

(8, 2, 2)

(8, 2, 2, 1)


In [9]:
a = np.arange(1, 10)
b = a[np.newaxis, :]
print(b.shape, end = '\n\n')
c = a[np.newaxis, :, np.newaxis]
print(c.shape)

(1, 9)

(1, 9, 1)


In [10]:
# Обьединение и разделение массивов
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])
print(np.hstack([a, b]), end = '\n\n')
print(np.vstack([b, a]), end = '\n\n')
print(np.vstack([b, a, a]))

[[1 2 5 6]
 [3 4 7 8]]

[[5 6]
 [7 8]
 [1 2]
 [3 4]]

[[5 6]
 [7 8]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]


In [13]:
a = np.fromiter(range(18), dtype = 'int32')
b = np.fromiter(range(18, 36), dtype = 'int32')
a.resize(3, 3, 2)
b.resize(3, 3, 2)
c = np.hstack([a, b])
print(c.shape, end = '\n\n')
d = np.vstack([a, b])
print(d.shape, end = '\n\n')

(3, 6, 2)

(6, 3, 2)



In [20]:
a = np.array([1., 2., 3., 4.])
b = np.array([5., 6., 7., 8.])
c = np.column_stack([a, b])
print(c, end = '\n\n')
d = np.row_stack([a, b])
print(d)

[[1. 5.]
 [2. 6.]
 [3. 7.]
 [4. 8.]]

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [27]:
a = np.arange(1, 13)
b = np.arange(13, 26)
a.resize(3, 3, 2)
b.resize(3, 3, 2)
c0 = np.concatenate([a, b], axis = 0)
c1 = np.concatenate([a, b], axis = 1)
c2 = np.concatenate([a, b], axis = 2)
print(f'{c0.shape}, {c1.shape}, {c2.shape}')

(6, 3, 2), (3, 6, 2), (3, 3, 4)


In [31]:
print(np.r_[ [1, 2, 3], 4, 5], end = '\n\n')
print(np.r_[ 1:9, 90, 100], end = '\n\n')
print(np.r_[ np.array([1, 2, 3]), np.array([4, 5, 6])], end = '\n\n')
print(np.r_[ [(1, 2, 3), (4, 5, 6)], [(7, 8, 9)]], end = '\n\n')

print(np.c_[1:5], end = '\n\n')
print(np.r_[1:5], end = '\n\n')
print(np.c_[ [1, 2, 3], [4, 5, 6]], end = '\n\n')
print(np.c_[ [(1, 2, 3), (4, 5, 6)], [[7], [8]]])

[1 2 3 4 5]

[  1   2   3   4   5   6   7   8  90 100]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1]
 [2]
 [3]
 [4]]

[1 2 3 4]

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3 7]
 [4 5 6 8]]


In [39]:
a = np.arange(10)
print(np.hsplit(a, 2), end = '\n\n')
print(np.hsplit(a, 5), end = '\n\n')
a.resize(2, 6)
print(np.vsplit(a, 2), end = '\n\n')
print(np.hsplit(a, 6))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

[array([[0, 1, 2, 3, 4, 5]]), array([[6, 7, 8, 9, 0, 0]])]

[array([[0],
       [6]]), array([[1],
       [7]]), array([[2],
       [8]]), array([[3],
       [9]]), array([[4],
       [0]]), array([[5],
       [0]])]


In [40]:
a = np.arange(18)
a.resize(3, 3, 2)
print(np.array_split(a, 2, axis = 2), end = '\n\n')
print(np.array_split(a, 2, axis = 1), end = '\n\n')
print(np.array_split(a, 2, axis = 0))

[array([[[ 0],
        [ 2],
        [ 4]],

       [[ 6],
        [ 8],
        [10]],

       [[12],
        [14],
        [16]]]), array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]],

       [[13],
        [15],
        [17]]])]

[array([[[ 0,  1],
        [ 2,  3]],

       [[ 6,  7],
        [ 8,  9]],

       [[12, 13],
        [14, 15]]]), array([[[ 4,  5]],

       [[10, 11]],

       [[16, 17]]])]

[array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]]), array([[[12, 13],
        [14, 15],
        [16, 17]]])]


In [44]:
# Индексация, срезы, итерирование массивов
a = np.arange(12)
print(a[2], end = '\n\n')
a[0] = 100
print(a, end = '\n\n')
b = a[2:4]
print(b, end = '\n\n')
a[:4] = [-1, -2, -3, -4]
print(a, end = '\n\n')
a[4::2] = np.array([10, 20, 30, 40])
print(a, end = '\n\n')
for x in a:
    print(x, end = ' ')

2

[100   1   2   3   4   5   6   7   8   9  10  11]

[2 3]

[-1 -2 -3 -4  4  5  6  7  8  9 10 11]

[-1 -2 -3 -4 10  5 20  7 30  9 40 11]

-1 -2 -3 -4 10 5 20 7 30 9 40 11 

In [50]:
x = np.array([(1, 2, 3), (10, 20, 30), (100, 200, 300)])
print(x[1, 1], x[-1, -1], x[0], x[1], x[0, :], x[:, 1], end = '\n\n')
for row in x:
    for val in row:
        print(val, end = ' ')
    print()
print()
    
for val in x.flat:
    print(val, end = ' ')

20 300 [1 2 3] [10 20 30] [1 2 3] [  2  20 200]

1 2 3 
10 20 30 
100 200 300 

1 2 3 10 20 30 100 200 300 

In [53]:
a = np.arange(1, 82).reshape(3, 3, 3, 3)
print(a[1, 2, 0, 1], end = '\n\n')
print(a[:, 1, :, :], end = '\n\n')
print(a[0, 0], end = '\n\n') # = print(a[0, 0, :, :])
print(a[0:2, 0:2, 1, 1], end = '\n\n')
print(a[..., 1, 1])

47

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]

 [[64 65 66]
  [67 68 69]
  [70 71 72]]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 5 14]
 [32 41]]

[[ 5 14 23]
 [32 41 50]
 [59 68 77]]


In [56]:
a = np.arange(1, 9)
print(a, end = '\n\n')
b = a[[0]]
print(b, end = '\n\n')
b[0] = 100
print(b, end = '\n\n')
print(a[[0, 1, 7, 5]], end = '\n\n')
print(a[[0, 0, 1, 1, 1, 2, 3, 4, 5, 6, 7]], end = '\n\n')
a[[0, 1, 7, 5]] = [10, 20, 30, 40]
print(a)

[1 2 3 4 5 6 7 8]

[1]

[100]

[1 2 8 6]

[1 1 2 2 2 3 4 5 6 7 8]

[10 20  3  4  5 40  7 30]


In [58]:
index = [0, 0, 1, 1, 1, 2]
print(a[index], end = '\n\n')
index = np.array(index)
print(a[index], end = '\n\n')
bIndex = [True, True, False, False, False, True, False, False]
print(a[bIndex], end = '\n\n')
i = a > 5
print(a, end = '\n\n')
print(a[i], end = '\n\n')
print(a[a > 5])

[10 10 20 20 20  3]

[10 10 20 20 20  3]

[10 20 40]

[10 20  3  4  5 40  7 30]

[10 20 40  7 30]

[10 20 40  7 30]


In [63]:
a = np.arange(1, 9)
i = np.array([[0, 1], [2, 3]])
print(i, end = '\n\n')
print(a[i], end = '\n\n')
a= np.arange(1, 13).reshape(3, 4)
indx = [2, 1, 0]
print(a[indx], end = '\n\n')
indx = np.array([[1, 0], [2, 1]])
print(a[indx], end = '\n\n')
i0 = [0, 1]
i1 = [1, 2]
print(a[i0, i1], end = '\n\n')
print(a[:, i1], end = '\n\n')
print(a[i0, 1])

[[0 1]
 [2 3]]

[[1 2]
 [3 4]]

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

[[[ 5  6  7  8]
  [ 1  2  3  4]]

 [[ 9 10 11 12]
  [ 5  6  7  8]]]

[2 7]

[[ 2  3]
 [ 6  7]
 [10 11]]

[2 6]


In [64]:
a = np.arange(7)
a[[0, 4, 6]] = [-1, -2, -3]
print(a, end = '\n\n')
a[[0, 0, 0, 1]] = [1, 2, 3, 100]
print(a, end = '\n\n')
a[[0, 0, 0]] = a[[0, 0, 0]] + 3
print(a, end = '\n\n')  # эквивалентно a[0] = a[0] + 3
a[[0, 0, 1, 2]] += 1  # эквивалентно a[[0, 1, 2]] += 1
print(a)

[-1  1  2  3 -2  5 -3]

[  3 100   2   3  -2   5  -3]

[  6 100   2   3  -2   5  -3]

[  7 101   3   3  -2   5  -3]


In [67]:
# Базовые математические оперции над массивами
lst = [1, 2, 3]
a = np.array([1, 2, 3])
print(lst * 2)
print(a * 2, end = '\n\n')
print(-a, end = '\n\n')
print(a - 3, end = '\n\n')
print(a ** 3, end = '\n\n')
b = np.array([3, 4, 5])
print(a + b, end = '\n\n')
print(a / b, end = '\n\n')
print(b % a)

[1, 2, 3, 1, 2, 3]
[2 4 6]

[-1 -2 -3]

[-2 -1  0]

[ 1  8 27]

[4 6 8]

[0.33333333 0.5        0.6       ]

[0 0 2]


In [71]:
a = np.arange(1, 19)
a.resize(3, 3, 2)
b = np.ones((3, 2))
print(a - b, end = '\n\n')
print(a * 10, end = '\n\n')
print(a // b)

[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]
  [16. 17.]]]

[[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[ 70  80]
  [ 90 100]
  [110 120]]

 [[130 140]
  [150 160]
  [170 180]]]

[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]

 [[13. 14.]
  [15. 16.]
  [17. 18.]]]


In [75]:
a = np.array([1, 2, 6, 8])
a += 5
print(a, end = '\n\n')
a **= 2
print(a, end = '\n\n')
b = np.ones(4)
a -= 1
print(a)

[ 6  7 11 13]

[ 36  49 121 169]

[ 35  48 120 168]


In [78]:
# Булевы операции и функции, значения inf и nan
a = np.array([1, 2, 3, 10, 20, 30])
print(a[a > 5], end = '\n\n')
b = np.array([1, 2, 3, 4, 5 ,6])
print(a == b, end = '\n\n')
print(np.greater(a, b), end = '\n\n')
print(np.less(a, b), end = '\n\n')
print(np.equal(a, b), end = '\n\n')
print(np.array_equal(a, b), '\n\n')
print(np.any(a > 5), end = '\n\n')
print(np.any(a == 5), end = '\n\n')
print(np.all(a > 5), end = '\n\n')
print(np.all(a > 0))

[10 20 30]

[ True  True  True False False False]

[False False False  True  True  True]

[False False False False False False]

[ True  True  True False False False]

False 


True

False

False

True


In [80]:
a = np.arange(1, 9)
print(a / 0, end = '\n\n')
b = np.array([1, 2, np.inf])
print(b * 0, end = '\n\n')
c = b * 0
print(c.sum(), end = '\n\n')
b = np.array([1, 2, np.nan, np.inf, -np.inf])
print(np.isinf(b), end = '\n\n')
print(np.isnan(b), end = '\n\n')
indx = np.isinf(b)
print(b, end = '\n\n')
print(b[~indx], end = '\n\n')  # ~ инвертирует значения массива indx, а затем, проведя индексацию по массиву, мы откидываем значения равные inf
print(np.isfinite(b), end = '\n\n')
a = np.array([1 + 2j, 3 - 4j, 5])
print(np.iscomplex(a), end = '\n\n')
print(np.isreal(a))

[inf inf inf inf inf inf inf inf]

[ 0.  0. nan]

nan

[False False False  True  True]

[False False  True False False]

[  1.   2.  nan  inf -inf]

[ 1.  2. nan]


/var/folders/l9/88y_46d53y3cy1jh1h6qdg0c0000gn/T/ipykernel_70988/2183991894.py:2: RuntimeWarning: divide by zero encountered in divide
  print(a / 0, end = '\n\n')
/var/folders/l9/88y_46d53y3cy1jh1h6qdg0c0000gn/T/ipykernel_70988/2183991894.py:4: RuntimeWarning: invalid value encountered in multiply
  print(b * 0, end = '\n\n')
/var/folders/l9/88y_46d53y3cy1jh1h6qdg0c0000gn/T/ipykernel_70988/2183991894.py:5: RuntimeWarning: invalid value encountered in multiply
  c = b * 0


In [81]:
X = np.array([True, False, True, False])
Y = np.array([True, True, False, False])
print(np.logical_and(X, Y), end = '\n\n')
print(np.logical_or(X, Y), end = '\n\n')
print(np.logical_not(X, Y), end = '\n\n')
print(np.logical_xor(X, Y), end = '\n\n')

a = np.array([1, 0, 2, 0]) 
b = np.array([5, 4, 0, 0])
print(np.logical_and(a, b))

[ True False False False]

[ True  True  True False]

[False  True False  True]

[ True  True  True  True]

[ True False False False]


In [84]:
# Базовые математические функции
a = np.array([1, 2, 3, 10, 20, 30])
print(a.sum(), a.mean(), a.max(), a.min(), end = '\n\n') # mean - среднее арифметическое
a.resize(3, 2)
print(a.sum(axis = 0), a.sum(axis = 1), a.max(axis = 0), a.max(axis = 1), end = '\n\n')
a = np.array([-1, 1, 5, -44, 32, 2])
print(np.abs(a), end = '\n\n')
print(np.abs(-10.5), end = '\n\n')
print(np.abs([-10.5, -2, 5]), end = '\n\n')
print(np.amax(a), np.amin(a), end = '\n\n')
print(np.round(0.7), np.round(0.5), end = '\n\n')
print(np.argmax(a), np.argmin(a), end = '\n\n')
a.resize(2, 3)
print(np.amax(a, axis = 0), np.amin(a, axis = 1))

66 11.0 30 1

[24 42] [ 3 13 50] [20 30] [ 2 10 30]

[ 1  1  5 44 32  2]

10.5

[10.5  2.   5. ]

32 -44

1.0 0.0

4 3

[-1 32  5] [ -1 -44]


In [85]:
a = np.random.rand(10) # генерация чисел с равномерным законом распределения
print(a, end = '\n\n')
a = np.random.randint(5, 10, size = (2, 5)) # генерация целых чисел с равномерным законом распределения
print(a, end = '\n\n')
a = np.random.randn(2, 3) # генерация нормальных случайных значений
print(a, end = '\n\n')
a = np.random.pareto(2.0, size = 3)
print(a, end = '\n\n')
a = np.random.beta(0.1, 0.3, size = (3, 3))
print(a, end = '\n\n')
np.random.seed(13)
print(np.random.randint(10, size = 10), end = '\n\n')
np.random.seed(13)
print(np.random.randint(10, size = 10))

[0.3832213  0.68506409 0.50342687 0.32388853 0.98022917 0.5375729
 0.96457832 0.18684731 0.45318891 0.67003954]

[[8 5 7 5 5]
 [8 5 7 5 6]]

[[-0.33816105  0.59055621  0.52196544]
 [-1.01959765 -1.02235982  2.04899632]]

[1.17682234 0.61447629 0.13639783]

[[1.40458521e-05 2.96099266e-03 9.99729672e-01]
 [6.68680654e-01 2.34831692e-01 5.92384998e-13]
 [1.78694035e-04 3.98227624e-08 8.99575550e-01]]

[2 0 0 6 2 4 9 3 4 2]

[2 0 0 6 2 4 9 3 4 2]


In [4]:
a = np.arange(10)
np.random.shuffle(a) # элементы массива случайным образом перетасовываются, но только по первой оси
print(a, end = '\n\n')
a = np.arange(1, 10).reshape(3, 3)
np.random.shuffle(a)
print(a, end = '\n\n')
print(np.random.permutation(10), end = '\n\n')

[4 3 6 7 0 1 8 2 9 5]

[[4 5 6]
 [1 2 3]
 [7 8 9]]

[2 0 6 5 1 8 3 7 4 9]



In [5]:
x = np.array([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = np.array([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])
print(np.median(x), end = '\n\n') # вычисление медианы величин x
print(np.var(x), end = '\n\n') # дисперсия величин x
print(np.std(x), end = '\n\n') # среднеквадратическое отклонение величин x
XY = np.vstack([x, y]) 
print(XY, end = '\n\n') 
print(np.corrcoef(XY)) # линейный коэффицент корреляции Пирсона
print(np.cov(XY), end = '\n\n') # вычисление ковариационной матрицы
print(np.correlate(x, y)) # вычисление кросс-корреляции

9.0

57.29

7.569015788066504

[[ 1  4  3  7 10  8 14 21 20 23]
 [ 4  1  6  9 13 11 16 19 15 22]]

[[1.         0.93158099]
 [0.93158099 1.        ]]
[[63.65555556 49.82222222]
 [49.82222222 44.93333333]]

[1736]


In [10]:
# Произведение матриц и векторов, элементы линейной алгебры
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)
print(np.dot(a, b), end= '\n\n')  # матричное умножение
print(np.dot(b, a), end = '\n\n')
print(np.matmul(a, b), end = '\n\n') # тоже матричное умножение, лучше использовать его
a = np.arange(1, 10)
b = np.ones(9)
print(np.inner(a, b), end = '\n\n') # внутреннее умножение векторов
print(np.outer(a, b), end = '\n\n') # внешнее умножение векторов
print(a @ b, end = '\n\n') # внутреннее умножение векторов
a.resize(3, 3)
b.resize(3, 3)
print(a @ b, end = '\n\n') # матричное умножение
a = np.array([1, 2, 3])
b = np.arange(4, 10).reshape(3, 2)
print(np.dot(a, b), end = '\n\n') # умножение вектора на матрицу
a = np.array([1, 2])
print(np.dot(b, a), end = '\n\n') # умножение матрицы на вектор
a = a.T
print(b @ a) # умножение матрицы на вектор

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]

[[138 171 204]
 [174 216 258]
 [210 261 312]]

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]

45.0

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9.]]

45.0

[[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]

[40 46]

[14 20 26]

[14 20 26]


In [11]:
a = np.array([(1, 2, 3), (1, 4, 9), (1, 8, 27)])
y = np.array([10, 20, 30])
print(np.linalg.solve(a, y), end = '\n\n')
invA = np.linalg.inv(a)
print(invA, end = '\n\n')
print(a @ invA, end = '\n\n')
print(invA @ y)

[-5.         10.         -1.66666667]

[[ 3.         -2.5         0.5       ]
 [-1.5         2.         -0.5       ]
 [ 0.33333333 -0.5         0.16666667]]

[[ 1.00000000e+00  1.11022302e-16  5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00  1.66533454e-16]
 [ 7.21644966e-16  5.55111512e-16  1.00000000e+00]]

[-5.         10.         -1.66666667]


In [ ]:
# np.linalg.cholesky() - Разложение Холецкого
# np.linalg.qr() - QR-разложение матрицы
# np.linalg.svd() - Сингулярное(SVD) разложение матрицы
# np.linalg.norm() - Норма матрицы или вектора
# np.linalg.cond() - Число обусловленности матрицы
# np.linalg.det() - Детерминант матрицы
# np.linalg.matrix_rank() - Вычисление ранга матрицы по алгоритму SVD
# np.trace() - След матрицы
# np.linalg.eig() - Вычисление собственных значений и правых собственных векторов
# np.linalg.eigvals() - Вычисление собственных значений матрицы
# np.linalg.solve() - Решение линейного матричного уравнения
# np.linalg.tensorsolve() - Решение линейного тензорного уравнения
# np.linalg.lstq() - Решает задачу поиска наименьших квадратов для линейного матричного уравнения
# np.linalg.inv() - Вычисление обратной матрицы
# np.linalg.pinv() - Вычисление псевдообратной матрицы(Мура-Пенроуза) матрицы
# np.linalg.tensorinv() - Вычисление обратного тензора(N-мерного массива)

In [13]:
# Множества(unique) и операции над ними
a = np.array([1, 2, 3, 4, 4, 3, 2, 1])
setA = np.unique(a)
print(setA, end = '\n\n')
print(np.unique(a, return_counts = True), end = '\n\n') # return_counts возвращает количество повторов входящих элементов
print(np.unique(a, return_index = True), end = '\n\n') # return_index возвращает индексы первого вхождения уникальных элементов
print(np.unique(a, return_inverse = True), end = '\n\n') # return_inverse возвращает индексы, по которым можно точно вернуть первоначальный массив
setA, indx = np.unique(a, return_inverse = True)
print(setA, end = '\n\n')
print(indx, end = '\n\n')
print(setA[indx], end = '\n\n')
x = np.array([[0, 1, 1, 2], [0, 1, 1, 2], [9, 1, 1, 2]])
print(np.unique(x), end = '\n\n')
print(np.unique(x, axis = 0), end = '\n\n')
print(np.unique(x, axis = 1))

[1 2 3 4]

(array([1, 2, 3, 4]), array([2, 2, 2, 2]))

(array([1, 2, 3, 4]), array([0, 1, 2, 3]))

(array([1, 2, 3, 4]), array([0, 1, 2, 3, 3, 2, 1, 0]))

[1 2 3 4]

[0 1 2 3 3 2 1 0]

[1 2 3 4 4 3 2 1]

[0 1 2 9]

[[0 1 1 2]
 [9 1 1 2]]

[[0 1 2]
 [0 1 2]
 [9 1 2]]


In [15]:
x = np.array([0, 1, 2, 3])
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.in1d(x, y), end = '\n\n')
np.random.shuffle(y)
print(np.in1d(x, y), end = '\n\n')
print(np.intersect1d(x, y), end = '\n\n')
print(np.union1d(x, y), end = '\n\n')
print(np.setdiff1d(x, y), end = '\n\n')
print(np.setdiff1d(y, x), end = '\n\n')
print(np.setxor1d(x, y))

[False  True  True  True]

[False  True  True  True]

[1 2 3]

[0 1 2 3 4 5 6 7 8]

[0]

[4 5 6 7 8]

[0 4 5 6 7 8]


In [20]:
# Транслирование массивов
a = np.array([1, 2, 3, 10, 20, 30])
b = np.array([2])
print(a * b, end = '\n\n')
print(a + b, end = '\n\n')
b = np.array([2, 3])
# a * b ValueError 
# Правила транслирования массивов:
# 1. Если массивы имеют разное число осей(размерность), то к массиву с
# меньшим их числом добавляются новые так, чтобы размерности совпадали
# (Причем добавление всегда происходит с axis0)
# 2. Оси с одним элементом расширяются(по числу элементов) так, чтобы
# соответствующие размерности двух массивов совпадали
a = np.arange(1, 10).reshape(3, 3)
b = np.array([4, 5, 6])
print(a + b, end = '\n\n')
a = np.arange(6).reshape(3, 1, 2)
b = np.ones(4).reshape(2, 2)
print(a * b, (a * b).shape, end = '\n\n')
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([7, 8, 9, 10])
a.shape = 1, 1, -1
b.shape = 1, -1, 1
c.shape = -1, 1, 1
print(a * b + c, (a * b + c).shape, end = '\n\n')
# но можно сделать это действие и легче:
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([7, 8, 9, 10])
an, bn, cn = np.ix_(a, b, c) # но оно работает только с одномерными массивами
print(an.shape, bn.shape, cn.shape, end = '\n\n')
print(an * bn + cn, (an * bn + cn).shape)

[ 2  4  6 20 40 60]

[ 3  4  5 12 22 32]

[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]

[[[0. 1.]
  [0. 1.]]

 [[2. 3.]
  [2. 3.]]

 [[4. 5.]
  [4. 5.]]] (3, 2, 2)

[[[11 15 19]
  [12 17 22]]

 [[12 16 20]
  [13 18 23]]

 [[13 17 21]
  [14 19 24]]

 [[14 18 22]
  [15 20 25]]] (4, 2, 3)

(3, 1, 1) (1, 2, 1) (1, 1, 4)

[[[11 12 13 14]
  [12 13 14 15]]

 [[15 16 17 18]
  [17 18 19 20]]

 [[19 20 21 22]
  [22 23 24 25]]] (3, 2, 4)
